In [2]:

import torch

a1 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)
print("Tensor a1:\n", a1)
print(f"Kích thước (shape): {a1.shape}")
print(f"Số chiều (ndim): {a1.ndim}")
print(f"Kiểu dữ liệu (dtype): {a1.dtype}")

Tensor a1:
 tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kích thước (shape): torch.Size([2, 3])
Số chiều (ndim): 2
Kiểu dữ liệu (dtype): torch.int32


In [3]:



a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print("rand (uniform [0,1)):\n", a)
print("randn (normal distribution):\n", b)
print("zeros:\n", c)
print("ones:\n", d)
print("eye(4):\n", e)

# Tensor kích thước 5x5 chứa toàn giá trị 10
tensor_10 = torch.full((5, 5), 10)
print("Tensor 5x5 toàn giá trị 10:\n", tensor_10)

rand (uniform [0,1)):
 tensor([[0.7380, 0.0664, 0.5173, 0.4320],
        [0.7735, 0.0273, 0.1252, 0.4904],
        [0.4567, 0.5369, 0.0075, 0.1798]])
randn (normal distribution):
 tensor([[-0.3911,  0.5281, -0.9418,  0.9846],
        [ 0.6309,  0.0546,  0.6602,  0.1027],
        [-0.6631,  0.1897,  1.2513, -0.2685]])
zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
eye(4):
 tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Tensor 5x5 toàn giá trị 10:
 tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


In [1]:
import torch

a3 = torch.zeros(2, 3, 4)
print("Tensor:\n", a3)
print("Shape:", a3.shape)
print("Size:", a3.size())
print("Number of dimensions:", a3.ndim)
print("Data type:", a3.dtype)

Tensor:
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


In [2]:
import torch

a4 = torch.randn(3, 4, 5)
print("Original tensor shape:", a4.shape)
print("a shape:", a4.shape)
print("a[1:, 2:4] shape:", a4[1:, 2:4].shape)

# Hai phần tử cuối cùng trên chiều thứ ba của a4
print("Hai phần tử cuối cùng chiều 3:\n", a4[..., -2:])

Original tensor shape: torch.Size([3, 4, 5])
a shape: torch.Size([3, 4, 5])
a[1:, 2:4] shape: torch.Size([2, 2, 5])
Hai phần tử cuối cùng chiều 3:
 tensor([[[-0.2865, -0.3825],
         [-1.0867, -0.4807],
         [ 0.6439,  0.2507],
         [ 1.8150,  0.5791]],

        [[-2.3779,  0.3408],
         [-0.3263,  1.1732],
         [ 0.3460, -0.4256],
         [ 1.1237,  0.1838]],

        [[ 0.4481, -0.9189],
         [ 0.6295, -0.5939],
         [-0.8403,  0.6167],
         [ 1.1889,  2.1739]]])


In [3]:
import torch

a5 = torch.randn(3, 4)
print("Original shape:", a5.shape, "| Tổng số phần tử:", a5.numel())
flat_a5 = a5.ravel()
print("Flatten shape:", flat_a5.shape, "| Tổng số phần tử:", flat_a5.numel())
reshaped_2_6 = a5.reshape(2, 6)
print("Reshape 2x6 shape:", reshaped_2_6.shape, "| Tổng số phần tử:", reshaped_2_6.numel())

Original shape: torch.Size([3, 4]) | Tổng số phần tử: 12
Flatten shape: torch.Size([12]) | Tổng số phần tử: 12
Reshape 2x6 shape: torch.Size([2, 6]) | Tổng số phần tử: 12


In [4]:
import torch

a6 = torch.randn(2, 3)
b6 = torch.randn(2, 3)
print("a6 * b6 (element-wise):\n", a6 * b6)

mat_mul = a6 @ b6.T
print("a6 @ b6.T shape:", mat_mul.shape)

a6 * b6 (element-wise):
 tensor([[-0.0208,  0.0243,  0.0632],
        [-0.6934,  0.2366,  1.1135]])
a6 @ b6.T shape: torch.Size([2, 2])


In [5]:
import torch

a7 = torch.randn(3, 4)
print("Mean dim=0:\n", torch.mean(a7, dim=0))
print("Mean dim=1:\n", torch.mean(a7, dim=1))
print("Std dim=0:\n", torch.std(a7, dim=0))
print("Std dim=1:\n", torch.std(a7, dim=1))
print("Cumsum dim=0:\n", torch.cumsum(a7, dim=0))
print("Cumsum dim=1:\n", torch.cumsum(a7, dim=1))

Mean dim=0:
 tensor([1.2952, 0.4763, 0.2418, 0.1896])
Mean dim=1:
 tensor([0.3308, 0.6970, 0.6244])
Std dim=0:
 tensor([0.1353, 0.1558, 0.8733, 0.6028])
Std dim=1:
 tensor([0.6743, 0.7497, 0.6691])
Cumsum dim=0:
 tensor([[ 1.1738,  0.5044, -0.4083,  0.0532],
        [ 2.4446,  1.1205,  0.8262, -0.2800],
        [ 3.8857,  1.4290,  0.7254,  0.5689]])
Cumsum dim=1:
 tensor([[1.1738, 1.6782, 1.2700, 1.3231],
        [1.2708, 1.8869, 3.1214, 2.7882],
        [1.4411, 1.7495, 1.6486, 2.4976]])


In [6]:
import torch

x8 = torch.tensor(3.6, requires_grad=True)
y8 = x8 * x8
y8.backward()
print("x8.grad (y = x² tại x=3.6):", x8.grad.item())
print("Đạo hàm thủ công 2x =", 2 * 3.6)

# Nâng cao: y = 3x² + 2x + 1
x8_2 = torch.tensor(3.6, requires_grad=True)
y8_2 = 3 * x8_2**2 + 2 * x8_2 + 1
y8_2.backward()
print("x8_2.grad (y = 3x² + 2x + 1):", x8_2.grad.item())
print("Đạo hàm thủ công 6x + 2 =", 6*3.6 + 2)

x8.grad (y = x² tại x=3.6): 7.199999809265137
Đạo hàm thủ công 2x = 7.2
x8_2.grad (y = 3x² + 2x + 1): 23.599998474121094
Đạo hàm thủ công 6x + 2 = 23.6


In [10]:
import torch
import numpy as np

np.random.seed(42)
torch.manual_seed(42)

# Đa thức bậc 2: 2x² + 3x + 1
polynomial9 = np.poly1d([2, 3, 1])

N9 = 20
X9 = np.random.randn(N9, 1) * 5
Y9 = polynomial9(X9)

XX9 = np.hstack([X9 * X9, X9, np.ones_like(X9)])

w9 = torch.randn(3, 1, requires_grad=True)
x9 = torch.tensor(XX9, dtype=torch.float32)
y9 = torch.tensor(Y9, dtype=torch.float32)

optimizer9 = torch.optim.NAdam([w9], lr=0.01)

for epoch in range(1000):
    optimizer9.zero_grad()
    y_pred9 = x9 @ w9
    mse9 = torch.mean(torch.square(y9 - y_pred9))
    mse9.backward()
    optimizer9.step()

print("Learned coefficients:\n", w9.detach().numpy().flatten())

Learned coefficients:
 [1.9893595 2.9958193 1.5701371]


In [12]:
import torch
import random

random.seed(42)
torch.manual_seed(42)
A10 = torch.tensor(random.random(), requires_grad=True)
B10 = torch.tensor(random.random(), requires_grad=True)
C10 = torch.tensor(random.random(), requires_grad=True)
D10 = torch.tensor(random.random(), requires_grad=True)
optimizer10 = torch.optim.NAdam([A10, B10, C10, D10], lr=0.01)

for _ in range(2000):
    y1 = A10 + B10 - 9
    y2 = C10 - D10 - 1
    y3 = A10 + C10 - 8
    y4 = B10 - D10 - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer10.zero_grad()
    sqerr.backward()
    optimizer10.step()

print(f"A={A10.item():.4f}, B={B10.item():.4f}, C={C10.item():.4f}, D={D10.item():.4f}")

A=4.7772, B=4.2227, C=3.2228, D=2.2227


In [13]:
import torch
import numpy as np

# Ý 1
X11 = torch.arange(24, dtype=torch.float32)
print("Reshape 4x6 shape:", X11.reshape(4, 6).shape)
print("Reshape 2x12 shape:", X11.reshape(2, 12).shape)
print("Reshape 2x3x4 shape:", X11.reshape(2, 3, 4).shape)

# Ý 2
A11 = torch.randn(3, 4)
B11 = torch.randn(3, 4) + 1e-4
print("A+B:\n", A11 + B11)
print("A*B:\n", A11 * B11)
print("A/B:\n", A11 / B11)
print("Mean theo cột A:\n", torch.mean(A11, dim=0))
print("Std theo cột A:\n", torch.std(A11, dim=0))

# Ý 3
x11_3 = torch.tensor(2.0, requires_grad=True)
y11_3 = 2 * x11_3**2 + 5 * x11_3 + 3
y11_3.backward()
print("Autograd dy/dx tại x=2:", x11_3.grad.item())
print("Thủ công 4x+5 tại x=2:", 4*2 + 5)

# Ý 4
np.random.seed(42)
polynomial11_4 = np.poly1d([2, -3, 5])
N11 = 20
X11_arr = np.random.randn(N11, 1) * 5
Y11_arr = polynomial11_4(X11_arr)
XX11_arr = np.hstack([X11_arr * X11_arr, X11_arr, np.ones_like(X11_arr)])
x11_tensor = torch.tensor(XX11_arr, dtype=torch.float32)
y11_tensor = torch.tensor(Y11_arr, dtype=torch.float32)
w11_4 = torch.randn(3, 1, requires_grad=True)
optimizer11_4 = torch.optim.NAdam([w11_4], lr=0.01)

for _ in range(1000):
    optimizer11_4.zero_grad()
    y_pred11_4 = x11_tensor @ w11_4
    mse11_4 = torch.mean(torch.square(y11_tensor - y_pred11_4))
    mse11_4.backward()
    optimizer11_4.step()
print("Hệ số học được cho y = 2x² - 3x + 5:\n", w11_4.detach().numpy().flatten())

Reshape 4x6 shape: torch.Size([4, 6])
Reshape 2x12 shape: torch.Size([2, 12])
Reshape 2x3x4 shape: torch.Size([2, 3, 4])
A+B:
 tensor([[ 1.4471, -1.5609, -0.7544,  1.1884],
        [ 0.1994,  0.6310,  1.4425, -1.3885],
        [ 1.8143,  0.9538,  0.2072,  1.6044]])
A*B:
 tensor([[ 0.3739, -0.2176, -0.2319,  0.2207],
        [-1.4847, -0.1523, -1.6909,  0.4788],
        [ 0.6245,  0.1835, -0.1753,  0.6435]])
A/B:
 tensor([[ 0.3032, -0.0762, -0.2371,  0.2404],
        [-0.8492, -0.2280, -2.8838,  0.8501],
        [ 0.3413,  0.3895, -1.6325,  1.0180]])
Mean theo cột A:
 tensor([-0.1082,  0.0699,  0.9925,  0.1339])
Std theo cột A:
 tensor([0.8810, 0.2325, 1.0635, 0.7285])
Autograd dy/dx tại x=2: 13.0
Thủ công 4x+5 tại x=2: 13
Hệ số học được cho y = 2x² - 3x + 5:
 [ 2.0417318 -2.9013855  3.00168  ]
